image: registry.gitlab.com/stonepreston/lmn:latest
stages:
  - build
  - test
  
build:
    stage: build
    before_script:
    - git submodule update --init --recursive --progress
    
    script:
    - cmake -B build -DCMAKE_BUILD_TYPE=Release
    - cmake --build build -j8
    - ./build/APP_artefacts/Release/APP 



test:
    stage: test
    script:
    - ./build/UnitTestRunner/UnitTestRunner_artefacts/Release/UnitTestRunner 

