#pragma once

enum AppCommands
{
    SHOW_SYNTH = 1,
    SHOW_DRUM,
    SHOW_EDIT,
    SHOW_TRACKS,
    SHOW_INSTRUMENTS_LIST,
    SHOW_EFFECTS_LIST,
    SELECT_LIST_ITEM,
    SHOW_MIXER,
    SHOW_SETTINGS,
    SHOW_ENGINE_PARAMETERS,
    SHOW_ADSR_PARAMETERS,
    SHOW_EFFECT_PARAMETERS,
    SHOW_LFO_PARAMETERS,
    SHOW_SYNTH_LIST,
    SHOW_DRUM_LIST,
    SHOW_PRESET_1,
    SHOW_PRESET_2,
    SHOW_PRESET_3,
    SHOW_PRESET_4,
    SHOW_PRESET_5,
    SHOW_PRESET_6,
    SHOW_PRESET_7,
    SHOW_PRESET_8,
    INCREMENT_ENCODER_1,
    DECREMENT_ENCODER_1,
    INCREMENT_ENCODER_2,
    DECREMENT_ENCODER_2,
    INCREMENT_ENCODER_3,
    DECREMENT_ENCODER_4,
    INCREMENT_PARAMETER_1,
    INCREMENT_PARAMETER_2,
    INCREMENT_PARAMETER_3,
    INCREMENT_PARAMETER_4,
    DECREMENT_PARAMETER_1,
    DECREMENT_PARAMETER_2,
    DECREMENT_PARAMETER_3,
    DECREMENT_PARAMETER_4


};