#pragma once

enum AppCommands
{
    SHOW_SYNTH = 1,
    SHOW_DRUM,
    SHOW_TAPE,
    SHOW_MIXER,
    SHOW_SETTINGS,
    SHOW_ENGINE_PARAMETERS,
    SHOW_ADSR_PARAMETERS,
    SHOW_EFFECT_PARAMETERS,
    SHOW_LFO_PARAMETERS

};