#pragma once

enum AppCommands
{
    SHOW_SYNTH = 1,
    SHOW_DRUM,
    SHOW_TAPE,
    SHOW_MIXER,
    SHOW_SETTINGS,
    SHOW_ENGINE_PARAMETERS,
    SHOW_ADSR_PARAMETERS,
    SHOW_EFFECT_PARAMETERS,
    SHOW_LFO_PARAMETERS,
    SHOW_SYNTH_LIST,
    SHOW_DRUM_LIST,
    SHOW_PRESET_1,
    SHOW_PRESET_2,
    SHOW_PRESET_3,
    SHOW_PRESET_4,
    SHOW_PRESET_5,
    SHOW_PRESET_6,
    SHOW_PRESET_7,
    SHOW_PRESET_8

};