name: release:master

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  test:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_compiler:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target Tests -j8
      - name: run unit tests
        run: |
          ./build/Tests/Tests_artefacts/Release/Tests

  release_x86_64:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_compiler:latest

    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: release
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j8
          cd ./build
          zip -r LMN3_x86_64.zip LMN3_artefacts/ Plugins/
      - uses: "softprops/action-gh-release@v1"
        with:
          name: latest[x86_64]
          tag_name: latest_x86_64
          files: |
            ./build/LMN3_x86_64.zip
            LICENSE

  release_arm:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_rpi4_cross_compiler:latest

    needs: test

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: release
        run: |
          cmake -B build-raspberry -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/toolchain/toolchain.cmake
          cmake --build build-raspberry --target APP -j8
          cd ./build-raspberry
          zip -r LMN3_arm.zip LMN3_artefacts/ Plugins/
      - uses: "softprops/action-gh-release@v1"
        with:
          name: latest[arm]
          tag_name: latest_arm
          files: |
            ./build/LMN3_arm.zip
            LICENSE
