name: release:master

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_compiler:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target Tests -j8
      - name: run unit tests
        run: |
          ./build/Tests/Tests_artefacts/Release/Tests
  pre_release_x86_64:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_compiler:latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j8
          cd ./build
          zip -r APP_x86_64.zip APP_artefacts/ Plugins/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest_x86_64]"
          prerelease: true
          title: "Development Build [x86_64]"
          files: |
            ./build/APP_x86_64.zip
  pre_release_arm:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_rpi4_cross_compiler:latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build-raspberry -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/toolchain/toolchain.cmake
          cmake --build build-raspberry -j8
          cd ./build-raspberry
          zip -r APP_arm.zip APP_artefacts/ Plugins/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest_arm"
          prerelease: true
          title: "Development Build [arm]"
          files: |
            ./build-raspberry/APP_arm.zip
