name: release:master

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_compiler:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target Tests -j8

      - name: run unit tests
        run: |
          ./build/Tests/Tests_artefacts/Release/Tests

  build:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_rpi4_cross_compiler:latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build-raspberry -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/toolchain/toolchain.cmake
          cmake --build build-raspberry --target APP -j8

      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}-${{ github.run_number }}
          release_name: Release ${{ github.ref }}-${{ github.run_number }}
          draft: true
          prerelease: true
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build-raspberry/APP_artefacts/Release/APP
          asset_name: APP
          asset_content_type: application



