name: tests:development

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    container: stonepreston/juce_compiler:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: build using cmake
        run: |
          cmake -B build -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_BUILD_TYPE=Release
          cmake --build build --target Tests -j8

      - name: run unit tests
        run: |
          ./build/Tests/Tests_artefacts/Release/Tests

